In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/New Bank_loan_data (1) (2) (1).csv')

In [3]:
df.head()

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,M,1,49.0,91107,4,1.6,1,0,Home Owner,0,1,0,0.0,0
1,2,45,M,19,34.0,90089,3,1.5,1,0,Rent,0,1,0,0.0,0
2,3,39,M,15,11.0,94720,1,1.0,1,0,Rent,0,0,0,0.0,0
3,4,35,M,9,100.0,94112,1,2.7,2,0,Rent,0,0,0,0.0,0
4,5,35,M,8,45.0,91330,4,1.0,2,0,Rent,0,0,0,0.0,1

In [4]:
df.shape

(5000, 16)

In [5]:
df.dtypes

ID                      int64
Age                     int64
Gender                 object
Experience              int64
Income                float64
ZIP Code                int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage                int64
Home Ownership         object
Personal Loan          object
Securities Account      int64
CD Account              int64
Online                float64
CreditCard              int64
dtype: object

In [6]:
df.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,4933.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4960.000000,5000.000000
mean,2500.500000,46.008200,20.104600,72.758159,93152.503000,2.396400,1.937938,1.880600,56.498800,0.104400,0.06040,0.596976,0.294000
std,1443.520003,25.444898,11.467954,45.425519,2121.852197,1.147663,1.747659,0.839812,101.713802,0.305809,0.23825,0.490555,0.455637
min,1.000000,0.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,63.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,95.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,978.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.00000,1.000000,1.000000

In [7]:
df.corr()

<ipython-input-7-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
ID,1.000000,-0.022173,-0.008326,-0.022748,0.013432,-0.016797,-0.024675,0.022141,-0.013920,-0.016972,-0.006909,-0.003776,0.017028
Age,-0.022173,1.000000,0.439132,0.026946,-0.022257,-0.017867,0.011776,0.024320,0.021672,-0.008234,0.022654,0.005506,-0.000087
Experience,-0.008326,0.439132,1.000000,-0.049319,-0.028626,-0.052563,-0.050077,0.014071,-0.010582,-0.001232,0.010353,0.013981,0.008967
Income,-0.022748,0.026946,-0.049319,1.000000,-0.018415,-0.167167,0.643782,-0.204080,0.201489,-0.004553,0.150053,0.011320,-0.008559
ZIP Code,0.013432,-0.022257,-0.028626,-0.018415,1.000000,0.011778,-0.004061,-0.017598,0.007383,0.004704,0.019972,0.017773,0.007691
Family,-0.016797,-0.017867,-0.052563,-0.167167,0.011778,1.000000,-0.109275,0.065098,-0.020445,0.019994,0.014110,0.010994,0.011588
CCAvg,-0.024675,0.011776,-0.050077,0.643782,-0.004061,-0.109275,1.000000,-0.136082,0.109905,0.015086,0.136534,-0.002082,-0.006689
Education,0.022141,0.024320,0.014071,-0.204080,-0.017598,0.065098,-0.136082,1.000000,-0.033482,-0.010650,0.014056,-0.014687,-0.010707
Mortgage,-0.013920,0.021672,-0.010582,0.201489,0.007383,-0.020445,0.109905,-0.033482,1.000000,-0.005411,0.089311,-0.005379,-0.007231
Securities Account,-0.016972,-0.008234,-0.001232,-0.004553,0.004704,0.019994,0.015086,-0.010650,-0.005411,1.000000,0.317034,0.011502,-0.015028
CD Account,-0.006909,0.022654,0.010353,0.150053,0.019972,0.014110,0.136534,0.014056,0.089311,0.317034,1.000000,0.171467,0.278644
Online,-0.003776,0.005506,0.013981,0.011320,0.017773,0.010994,-0.002082,-0.014687,-0.005379,0.011502,0.171467,1.000000,0.004159
CreditCard,0.017028,-0.000087,0.008967,-0.008559,0.007691,0.011588,-0.006689,-0.010707,-0.007231,-0.015028,0.278644,0.004159,1.000000

Checking for missing values

In [8]:
df.isna().sum()

ID                       0
Age                      0
Gender                1596
Experience               0
Income                  67
ZIP Code                 0
Family                   0
CCAvg                    0
Education                0
Mortgage                 0
Home Ownership        1189
Personal Loan            0
Securities Account       0
CD Account               0
Online                  40
CreditCard               0
dtype: int64

checking for duplicated values

In [9]:
df.duplicated().sum()

0

In [10]:
df['Home Ownership'].unique()

array(['Home Owner', 'Rent', 'Home Mortage', nan], dtype=object)

In [11]:
df['Gender'] = df['Gender'].replace(np.nan, 'not specified')
df['Gender'] = df['Gender'].replace(['#', '-'], 'not specified')

In [12]:
df['Gender'].isna().sum()

0

In [13]:
df_homeowner=df.loc[(df['Home Ownership']=='Home Owner') & (df['Mortgage']!=0)]
df_homerenter=df.loc[(df['Home Ownership']=='Rent') & (df['Mortgage']!=0)]

In [14]:
df_homeowner.shape

(378, 16)

In [15]:
df_homerenter.shape

(274, 16)

In [18]:
df.loc[(df['Home Ownership'].isna()) & (df['Mortgage'] != 0), 'Home Ownership'] = 'Home Owner'

In [21]:
df.isna().sum()

ID                      0
Age                     0
Gender                  0
Experience              0
Income                 67
ZIP Code                0
Family                  0
CCAvg                   0
Education               0
Mortgage                0
Home Ownership        841
Personal Loan           0
Securities Account      0
CD Account              0
Online                 40
CreditCard              0
dtype: int64

In [13]:
df_age

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
78,79,0,M,30,NaN,93305,2,2.6,3,0,Rent,1,0,0,0.0,0
1583,1584,0,F,36,184.0,92028,4,2.3,2,342,Rent,1,0,1,NaN,1

In [14]:
df_gender = df[df['Gender'].isna()]
df_gender

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
73,74,41,NaN,16,85.0,94606,1,4.0,3,0,Home Mortage,0,0,0,1.0,1
74,75,28,NaN,3,135.0,94611,2,3.3,1,0,Home Mortage,0,0,0,0.0,1
76,77,58,NaN,32,12.0,91320,3,0.3,3,0,Rent,0,0,0,0.0,0
77,78,46,NaN,20,29.0,92220,3,0.5,2,0,Rent,0,0,0,0.0,0
107,108,42,NaN,18,43.0,92037,1,0.7,1,136,Home Mortage,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,NaN,3,40.0,92697,1,1.9,3,0,NaN,0,0,0,1.0,0
4996,4997,30,NaN,4,15.0,92037,4,0.4,1,85,NaN,0,0,0,1.0,0
4997,4998,63,NaN,39,24.0,93023,2,0.3,3,0,NaN,0,0,0,0.0,0
4998,4999,65,NaN,40,49.0,90034,3,0.5,2,0,NaN,0,0,0,1.0,0
4999,5000,28,NaN,4,83.0,92612,3,0.8,1,0,NaN,0,0,0,1.0,1

In [15]:
df.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,4933.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4960.000000,5000.000000
mean,2500.500000,46.008200,20.104600,72.758159,93152.503000,2.396400,1.937938,1.880600,56.498800,0.104400,0.06040,0.596976,0.294000
std,1443.520003,25.444898,11.467954,45.425519,2121.852197,1.147663,1.747659,0.839812,101.713802,0.305809,0.23825,0.490555,0.455637
min,1.000000,0.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,63.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,95.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,978.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.00000,1.000000,1.000000

In [16]:
df['Gender'].nunique()

5

In [17]:
df['Gender'].unique()

array(['M', 'F', 'O', nan, '#', '-'], dtype=object)

In [18]:
df['Gender'].value_counts()

M    1677
F    1607
O      96
-      21
#       3
Name: Gender, dtype: int64

In [19]:
df['Gender'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
4995     True
4996     True
4997     True
4998     True
4999     True
Name: Gender, Length: 5000, dtype: bool

In [21]:
df.head()

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,M,1,49.0,91107,4,1.6,1,0,Home Owner,0,1,0,0.0,0
1,2,45,M,19,34.0,90089,3,1.5,1,0,Rent,0,1,0,0.0,0
2,3,39,M,15,11.0,94720,1,1.0,1,0,Rent,0,0,0,0.0,0
3,4,35,M,9,100.0,94112,1,2.7,2,0,Rent,0,0,0,0.0,0
4,5,35,M,8,45.0,91330,4,1.0,2,0,Rent,0,0,0,0.0,1