In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/New Bank_loan_data (1) (2) (1).csv')

In [ ]:
df.head()

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,M,1,49.0,91107,4,1.6,1,0,Home Owner,0,1,0,0.0,0
1,2,45,M,19,34.0,90089,3,1.5,1,0,Rent,0,1,0,0.0,0
2,3,39,M,15,11.0,94720,1,1.0,1,0,Rent,0,0,0,0.0,0
3,4,35,M,9,100.0,94112,1,2.7,2,0,Rent,0,0,0,0.0,0
4,5,35,M,8,45.0,91330,4,1.0,2,0,Rent,0,0,0,0.0,1

In [ ]:
df.shape

(5000, 16)

In [ ]:
df['Home Ownership'].nunique()

3

In [ ]:
df['Home Ownership'].value_counts()

Home Mortage    1705
Home Owner      1156
Rent             950
Name: Home Ownership, dtype: int64

In [ ]:
df_has_home = df[df['Home Ownership'].isna() & (df['Mortgage'] != 0)]
df_has_home

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
52,53,30,M,6,72.0,94005,1,0.10,1,207,NaN,0,0,0,0.0,0
327,328,58,M,32,114.0,91330,2,2.00,1,402,NaN,0,0,0,1.0,0
343,344,35,M,5,22.0,93407,1,0.67,3,103,NaN,0,0,0,0.0,0
373,374,49,M,25,20.0,90291,4,1.00,1,111,NaN,0,0,0,1.0,1
491,492,42,M,18,34.0,92115,4,0.30,1,104,NaN,0,1,0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,4988,48,NaN,23,43.0,93943,3,1.70,2,159,NaN,0,0,0,1.0,0
4988,4989,34,NaN,8,85.0,95134,1,2.50,1,136,NaN,0,0,0,0.0,1
4990,4991,55,NaN,25,58.0,95023,4,2.00,3,219,NaN,0,0,0,0.0,1
4991,4992,51,NaN,25,92.0,91330,1,1.90,2,100,NaN,0,0,0,0.0,1
4996,4997,30,NaN,4,15.0,92037,4,0.40,1,85,NaN,0,0,0,1.0,0

In [ ]:
df.isna().sum()

ID                       0
Age                      0
Gender                1596
Experience               0
Income                  67
ZIP Code                 0
Family                   0
CCAvg                    0
Education                0
Mortgage                 0
Home Ownership        1189
Personal Loan            0
Securities Account       0
CD Account               0
Online                  40
CreditCard               0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df_income_null = df[df['Income'].isna() | (df['Income'] == 0)]
df_income_null.head()

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
29,30,38,M,13,NaN,94104,1,3.3,2,0,Rent,1,0,1,1.0,1
38,39,42,M,18,NaN,94114,3,5.0,3,0,Rent,1,1,1,1.0,0
78,79,0,M,30,NaN,93305,2,2.6,3,0,Rent,1,0,0,0.0,0
199,200,36,M,11,NaN,92152,1,5.1,3,0,Home Mortage,1,0,1,1.0,1
324,325,56,M,30,NaN,90089,4,6.1,1,0,Rent,1,0,0,0.0,0

In [ ]:
df_income_null_sorted = df_income_null.sort_values(by='Age')
df_income_null_sorted

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
78,79,0,M,30,NaN,93305,2,2.6,3,0,Rent,1,0,0,0.0,0
4345,4346,26,O,1,NaN,94608,2,4.2,3,577,Home Owner,1,0,1,1.0,1
3084,3085,26,M,0,NaN,90028,3,0.7,2,0,Home Mortage,1,0,0,0.0,0
2951,2952,26,F,2,NaN,94720,2,2.4,3,0,Home Mortage,1,0,0,0.0,1
1022,1023,27,M,3,NaN,95605,1,3.3,2,0,Home Owner,1,0,0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3822,3823,63,F,33,NaN,91768,4,9.0,3,0,Home Mortage,1,0,0,0.0,0
2061,2062,63,M,38,NaN,93950,4,4.9,2,111,Home Mortage,1,0,0,0.0,0
4642,4643,65,O,40,NaN,95616,4,6.6,2,0,Home Mortage,1,0,0,1.0,0
1411,1412,65,F,39,NaN,91302,1,5.4,3,176,Home Owner,1,0,1,1.0,1
3217,3218,65,F,39,NaN,93022,4,4.1,1,120,Home Mortage,1,0,1,1.0,1

In [ ]:
df_age=df[df['Age']==0]

In [ ]:
df_age

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
78,79,0,M,30,NaN,93305,2,2.6,3,0,Rent,1,0,0,0.0,0
1583,1584,0,F,36,184.0,92028,4,2.3,2,342,Rent,1,0,1,NaN,1

In [ ]:
df_gender = df[df['Gender'].isna()]
df_gender

,ID,Age,Gender,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Home Ownership,Personal Loan,Securities Account,CD Account,Online,CreditCard
73,74,41,NaN,16,85.0,94606,1,4.0,3,0,Home Mortage,0,0,0,1.0,1
74,75,28,NaN,3,135.0,94611,2,3.3,1,0,Home Mortage,0,0,0,0.0,1
76,77,58,NaN,32,12.0,91320,3,0.3,3,0,Rent,0,0,0,0.0,0
77,78,46,NaN,20,29.0,92220,3,0.5,2,0,Rent,0,0,0,0.0,0
107,108,42,NaN,18,43.0,92037,1,0.7,1,136,Home Mortage,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,NaN,3,40.0,92697,1,1.9,3,0,NaN,0,0,0,1.0,0
4996,4997,30,NaN,4,15.0,92037,4,0.4,1,85,NaN,0,0,0,1.0,0
4997,4998,63,NaN,39,24.0,93023,2,0.3,3,0,NaN,0,0,0,0.0,0
4998,4999,65,NaN,40,49.0,90034,3,0.5,2,0,NaN,0,0,0,1.0,0
4999,5000,28,NaN,4,83.0,92612,3,0.8,1,0,NaN,0,0,0,1.0,1

In [ ]:
df.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,4933.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4960.000000,5000.000000
mean,2500.500000,46.008200,20.104600,72.758159,93152.503000,2.396400,1.937938,1.880600,56.498800,0.104400,0.06040,0.596976,0.294000
std,1443.520003,25.444898,11.467954,45.425519,2121.852197,1.147663,1.747659,0.839812,101.713802,0.305809,0.23825,0.490555,0.455637
min,1.000000,0.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,63.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,95.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,978.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.00000,1.000000,1.000000

In [ ]:
df['Gender'].nunique()

5

In [ ]:
df['Gender'].unique()

array(['M', 'F', 'O', nan, '#', '-'], dtype=object)

In [ ]:
df['Gender'].value_counts()

M    1677
F    1607
O      96
-      21
#       3
Name: Gender, dtype: int64

In [ ]:
df['Gender'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
4995     True
4996     True
4997     True
4998     True
4999     True
Name: Gender, Length: 5000, dtype: bool

In [ ]:
df['']